# Generated by Django 3.2.7 on 2021-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Аccent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('person-icon', 'PERSON-ICON'), ('question-icon', 'QUESTION-ICON'), ('lists-icon', 'LIST-ICON'), ('2dialog-icon', '2DIALOG-ICON'), ('book-icon', 'BOOK-ICON'), ('company-icon', 'COMPANY-ICON'), ('eurologo-icon', 'EUROLOGO-ICON')], default='person-icon"', max_length=13)),
                ('title', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
