# Generated by Django 3.2.7 on 2021-09-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
    ]
