# Generated by Django 3.2.7 on 2021-09-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210920_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='policies',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.policy'),
        ),
    ]
