# Generated by Django 3.2.7 on 2021-09-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20210921_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='uploads',
        ),
        migrations.AddField(
            model_name='policy',
            name='uploads',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='uploads', to='companies.PolicyUploads'),
        ),
    ]
