# Generated by Django 3.2.7 on 2021-09-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20210921_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='policies',
        ),
    ]
