# Generated by Django 3.2.7 on 2021-09-23 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_companies_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy', related_query_name='policy', to='companies.companies'),
        ),
    ]
