# Generated by Django 3.2.8 on 2021-10-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_policy_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='uploads',
        ),
    ]
